rules:
    default:
        protection:
          required_status_checks:
            contexts:
              - continuous-integration/travis-ci
              - codecov/project
          required_pull_request_reviews: null

        disabling_label: detekt-failed