rules:
  default:
    protection:
      required_status_checks:
        contexts:
          - continuous-integration/travis-ci
      required_pull_request_reviews:
        required_approving_review_count: 2
  branches:
    protection:
      stable/.*:
        required_pull_request_reviews:
          required_approving_review_count: 1