language: android

env:
    matrix:
        - ANDROID_TARGET=android-27 ANDROID_ABI=armeabi-v7a
    global:
        - ADB_INSTALL_TIMEOUT=10    #Time out to 10 mins

android:
        components:
                - platform-tools
                - build-tools-27.0.3
                - android-27
                - extra-android-m2repository

                # Additional components
#                - extra-google-google_play_services
#                - extra-google-m2repository
#                - extra-android-m2repository
#                - addon-google_apis-google-27

                # Specify at least one system image,
                # if you need to run emulator(s) during your tests
                - sys-img-armeabi-v7a-android-27
                - sys-img-armeabi-v7a-android-17

# Emulator Management: Create, Start and Wait
before_script:
        - chmod +x gradlew      #Grand permissions
        - android list targets
        - echo no | android create avd --force --name test --target $ANDROID_TARGET --abi $ANDROID_ABI    #Create AVD for given api
        - emulator -avd test -no-skin -no-audio -no-window &    #Start emulator
        - android-wait-for-emulator
        - adb devices   #Display list of devices
        - adb shell input keyevent 82 &
        - echo "Travis branch is $TRAVIS_BRANCH"
        - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"

script:
        - ./gradlew build
        - ./gradlew connectedCheck -PdisablePreDex --stacktrace
before_install:
        - yes | sdkmanager "platforms;android-27"
branches:
        only:
                - master